[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Readthedocs-template"
authors = [{name = "Jiapan Wang", email = "jiapan.wang@tum.de"}]
dynamic = ["version", "description"]
